### ISSUE TITLE
Can't store clothing in anything but locker

### ISSUE THREAD

**Issue by millehuse** [asquared31415/ONI-mods#1]
Might be missing something here, but when using this mod, the "clothing" category disappears from every other "storage" unit. This means I can't ship clothes to another planet with the teleporter. Is this intended?

**Comment by asquared31415** [comment]
Ah whoops, I will remove that restriction.  It was originally intended to remove it from just the normal storage bin, so that you wouldn't have your clothing split across everything.  But that list of allowed things is used lots of places.  I'll remove that change so that they can be put anywhere that would normally take them.

**Comment by asquared31415** [comment]
Updated in the latest version, 2.0.1
Use Mod Updater if steam doesn't show you the update within the next few hours

**Comment by millehuse** [comment]
Perfect, that did the trick! Thx for a very speedy upgrade.
